### ISSUE TITLE
Link to module "Adaptable Tools" goes to "document not found"

### ISSUE THREAD

**Issue by ghost** [w3c/personalization-semantics#70] opened 2018-04-23 13:53 UTC
In the Personalization Semantics Explainer 1.0 document, "Adaptable Tools" link should resolve to the appropriate document.

**Comment by becka11y** [comment] 2018-08-13 15:07
This is working for me on August 13, 2018. The link goes to:  https://w3c.github.io/personalization-semantics/tools/index.html.  Is this correct?

**Comment by clapierre** [comment] 2018-08-13 16:11
Agreed, this works for me as well.
Thanks
EOM

Charles LaPierre
Technical Lead, DIAGRAM and Born Accessible
Twitter: @CLaPierreA11Y
Skype: charles_lapierre
Phone: 650-600-3301



On Aug 13, 2018, at 8:07 AM, Becky Gibson <notifications@github.com<mailto:notifications@github.com>> wrote:


This is working for me on August 13, 2018. The link goes to: https://w3c.github.io/personalization-semantics/tools/index.html. Is this correct?

**Comment by thaddeus-cambron** [comment] 2018-08-13 16:19
Good Morning!

I believe I have this module assigned to me, however, I am confused about the work that needs to be done. At one point Sam and I were going to work on alternative technologies (web notifications) and there was a question about use cases. I listed both questions as response to issues. I am fine working on both on my own if needed.

Best,
Thaddeus
________________________________

**Comment by clapierre** [comment] 2018-08-27 12:59
Is this a duplicate of #69?
@ruoxiran status on this?

**Closed** 2020-02-28 08:09 UTC
Labels: editorial, explainer
